import Head from 'next/head'
import Image from 'next/image'
import s from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="hello">
          <div className="hello_title">
            Hello
          </div>
        </div>
      </div>
      
    </div>
  )
}
