import Head from 'next/head'

import { GiShrimp, GiFruitTree } from "react-icons/gi"
import { BsPiggyBank } from "react-icons/bs"
import { MdRecycling } from 'react-icons/md'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Organic Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='home_container'>
        <div className="home_banner">
          <div className="home_banner_content">
            <h2 className='home_banner_content_hello'>CHÀO MỪNG CÁC BẠN ĐẾN VỚI…</h2>
            <div className="home_banner_content_title_bio">BiO-MONA</div>
            <div className="home_banner_content_title_vn">Vietnam</div>
            <p className='home_banner_content_description'>Chúng tôi tự hào là doanh nghiệp đem đến những giải pháp ứng dụng công nghệ vi sinh tiên tiến nhất của Mỹ một cách độc quyền; đảm bảo chất lượng cho nguồn lương thực tại Việt Nam…</p>
            <div className="more_infomation">TÌM HIỂU THÊM</div>
          </div>
          <div className="home_banner_img_box">
            <img className="home_banner_img" src="https://mauweb.monamedia.net/huucomientrung/wp-content/uploads/2019/05/tumblr_pl4g3q2J1N1w3k1p5o1_640.gif" alt="banner" />
          </div>
        </div>
        <div className="technology_solution">
          <div className="technology_solution_title">Giải pháp công nghệ</div>
          <div className="technology_solution_content">AN TOÀN + HIỆU QUẢ = BỀN VỮNG</div>
          <div className="list_of_fields">
            <div className="list_of_fields_item col-lg-3 col-md-3 col-sm-6 col-6">
              <div className="list_of_fields_item_icon_box"><GiFruitTree className='list_of_fields_item_icon'/></div>
              <div className="list_of_fields_item_title">Lĩnh vực nông nghiệp</div>
              
            </div>
            <div className="list_of_fields_item col-lg-3 col-md-3 col-sm-6 col-6">
              <div className="list_of_fields_item_icon_box"><GiShrimp className='list_of_fields_item_icon'/></div>
              <div className="list_of_fields_item_title">Lĩnh vực thủy sản</div>
              
            </div>
            <div className="list_of_fields_item col-lg-3 col-md-3 col-sm-6 col-6">
              <div className="list_of_fields_item_icon_box"><BsPiggyBank className='list_of_fields_item_icon'/></div>
              <div className="list_of_fields_item_title">Lĩnh vực gia súc</div>
              
            </div>
            <div className="list_of_fields_item col-lg-3 col-md-3 col-sm-6 col-6">
              <div className="list_of_fields_item_icon_box"><MdRecycling className='list_of_fields_item_icon'/></div>
              <div className="list_of_fields_item_title">Lĩnh vực môi trường</div>
              
            </div>
          </div>
        </div>

      </div>
      
    </div>
  )
}
